version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: python app.py
    environment:
      - PYTHONUNBUFFERED=1
